name: cryptex
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  
flutter:
  uses-material-design: true
  assets:
    - assets/www/
    # ... at the very end of your pubspec.yaml file ...

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" # CHANGE THIS to the path of your logo
  min_sdk_android: 21 # Recommended for modern Android
